steps:
- task: AzureCLI@1
  displayName: 'Azure CLI $(System.DefaultWorkingDirectory)/_AzureAPIproducts-CI/product/deploy.bat'
  inputs:
    azureSubscription: 'Dev (f4a1ab46-ecfe-4834-b0f3-835c8d14e8bb)'
    scriptPath: '$(System.DefaultWorkingDirectory)/_AzureAPIproducts-CI/product/deploy.bat'
    workingDirectory: '$(System.DefaultWorkingDirectory)/_AzureAPIproducts-CI/product'
