steps:
- task: AzurePowerShell@3
  displayName: 'Azure PowerShell script: FilePath'
  inputs:
    azureSubscription: 'Dev (f4a1ab46-ecfe-4834-b0f3-835c8d14e8bb)'
    ScriptPath: '$(System.DefaultWorkingDirectory)/_OpenApiDeployment-CI/openapi/ImportSwaggerApi-OldModule.ps1'
    ScriptArguments: '-resourceGroupName API_Management -apimServiceName cubeapimgr-dev -apiId DemoConference -swaggerFile $(System.DefaultWorkingDirectory)/_OpenApiDeployment-CI/openapi/openApi.json -apiPath democonference'
    azurePowerShellVersion: LatestVersion