pool:
  name: Hosted
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: AzureAPIproductAssignment
    Contents: '**\*.json'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: apiproducts'
  inputs:
    ArtifactName: apiproducts